apiVersion: v1
kind: ServiceAccount
metadata:
  name: driftscape-coordinator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: driftscape-coordinator-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: driftscape-coordinator-binding
subjects:
- kind: ServiceAccount
  name: driftscape-coordinator
roleRef:
  kind: Role
  name: driftscape-coordinator-role
  apiGroup: rbac.authorization.k8s.io
