apiVersion: apps/v1
kind: Deployment
metadata:
  name: region-0-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: region
      x: "0"
      y: "0"
  template:
    metadata:
      labels:
        app: region
        x: "0"
        y: "0"
    spec:
      containers:
      - name: region
        image: driftscape-region
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: region-0-0
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: region
    x: "0"
    y: "0"
